name: CI

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run test:coverage
        run: pnpm test --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: pnpm/action-setup@v4

        - uses: actions/setup-node@v3
          with:
            node-version: '22'

        - name: Install dependencies
          run: pnpm install --frozen-lockfile

        - name: Run linter and formatter
          run: pnpm lint:ci
